### ISSUE TITLE
Categories for content 

### ISSUE THREAD

**Issue by YoshiKill** [czz/movian-plugin-tivix#3]
Hello. Thanks for you support tvix in movian. 
Can you add some categories for content, because when all chanels list loads its take to long to wait when its full load and you can watch.

**Comment by czz** [comment]
done on https://github.com/czz/movian-plugin-tivix/commit/e4d29263a2ac773899e3dbd2922366b1790bae18

**Comment by czz** [comment]
channels list now loads fast on b0e5d65
